### ISSUE TITLE
Is this production ready ?

### ISSUE THREAD

**Issue by WestFarmer** [MichaelVL/oidc-oauth2-bff#1]
Thanks for made this.
also looks similar to [oauth2-proxy](https://github.com/oauth2-proxy/oauth2-proxy), can author tell about difference ?
@MichaelVL

**Comment by michaelvl** [comment]
Hi,
Oauth2-proxy is a server-side solution. With oidc-oauth2-bff, the client-side is actively aware of the login session. This is useful for single-page-applications where the majority of the application is running client-side inside the browser. The accompanying example client (`main/src/index.ts`) is running in the browser and is capable of showing user information using Javascipt. With a server-side solution like oauth2-proxy, the client would be limited to show web-pages returned from the server-side.

**Comment by WestFarmer** [comment]
> The accompanying example client (main/src/index.ts) is running in the browser 

how can this be ? your oidc-oauth2-bff is a nodejs express web server, are you talking about some other repository
